// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	petstore "github.com/vaibhavk/petstore-apiserver/pkg/apis/petstore"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Pet)(nil), (*petstore.Pet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Pet_To_petstore_Pet(a.(*Pet), b.(*petstore.Pet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petstore.Pet)(nil), (*Pet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petstore_Pet_To_v1alpha1_Pet(a.(*petstore.Pet), b.(*Pet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PetStore)(nil), (*petstore.PetStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PetStore_To_petstore_PetStore(a.(*PetStore), b.(*petstore.PetStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petstore.PetStore)(nil), (*PetStore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petstore_PetStore_To_v1alpha1_PetStore(a.(*petstore.PetStore), b.(*PetStore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PetStoreList)(nil), (*petstore.PetStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PetStoreList_To_petstore_PetStoreList(a.(*PetStoreList), b.(*petstore.PetStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petstore.PetStoreList)(nil), (*PetStoreList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petstore_PetStoreList_To_v1alpha1_PetStoreList(a.(*petstore.PetStoreList), b.(*PetStoreList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PetStoreSpec)(nil), (*petstore.PetStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PetStoreSpec_To_petstore_PetStoreSpec(a.(*PetStoreSpec), b.(*petstore.PetStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petstore.PetStoreSpec)(nil), (*PetStoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petstore_PetStoreSpec_To_v1alpha1_PetStoreSpec(a.(*petstore.PetStoreSpec), b.(*PetStoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PetStoreStatus)(nil), (*petstore.PetStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PetStoreStatus_To_petstore_PetStoreStatus(a.(*PetStoreStatus), b.(*petstore.PetStoreStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*petstore.PetStoreStatus)(nil), (*PetStoreStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_petstore_PetStoreStatus_To_v1alpha1_PetStoreStatus(a.(*petstore.PetStoreStatus), b.(*PetStoreStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Pet_To_petstore_Pet(in *Pet, out *petstore.Pet, s conversion.Scope) error {
	out.Name = in.Name
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_Pet_To_petstore_Pet is an autogenerated conversion function.
func Convert_v1alpha1_Pet_To_petstore_Pet(in *Pet, out *petstore.Pet, s conversion.Scope) error {
	return autoConvert_v1alpha1_Pet_To_petstore_Pet(in, out, s)
}

func autoConvert_petstore_Pet_To_v1alpha1_Pet(in *petstore.Pet, out *Pet, s conversion.Scope) error {
	out.Name = in.Name
	out.Count = in.Count
	return nil
}

// Convert_petstore_Pet_To_v1alpha1_Pet is an autogenerated conversion function.
func Convert_petstore_Pet_To_v1alpha1_Pet(in *petstore.Pet, out *Pet, s conversion.Scope) error {
	return autoConvert_petstore_Pet_To_v1alpha1_Pet(in, out, s)
}

func autoConvert_v1alpha1_PetStore_To_petstore_PetStore(in *PetStore, out *petstore.PetStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PetStoreSpec_To_petstore_PetStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PetStoreStatus_To_petstore_PetStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PetStore_To_petstore_PetStore is an autogenerated conversion function.
func Convert_v1alpha1_PetStore_To_petstore_PetStore(in *PetStore, out *petstore.PetStore, s conversion.Scope) error {
	return autoConvert_v1alpha1_PetStore_To_petstore_PetStore(in, out, s)
}

func autoConvert_petstore_PetStore_To_v1alpha1_PetStore(in *petstore.PetStore, out *PetStore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_petstore_PetStoreSpec_To_v1alpha1_PetStoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_petstore_PetStoreStatus_To_v1alpha1_PetStoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_petstore_PetStore_To_v1alpha1_PetStore is an autogenerated conversion function.
func Convert_petstore_PetStore_To_v1alpha1_PetStore(in *petstore.PetStore, out *PetStore, s conversion.Scope) error {
	return autoConvert_petstore_PetStore_To_v1alpha1_PetStore(in, out, s)
}

func autoConvert_v1alpha1_PetStoreList_To_petstore_PetStoreList(in *PetStoreList, out *petstore.PetStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]petstore.PetStore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PetStoreList_To_petstore_PetStoreList is an autogenerated conversion function.
func Convert_v1alpha1_PetStoreList_To_petstore_PetStoreList(in *PetStoreList, out *petstore.PetStoreList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PetStoreList_To_petstore_PetStoreList(in, out, s)
}

func autoConvert_petstore_PetStoreList_To_v1alpha1_PetStoreList(in *petstore.PetStoreList, out *PetStoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PetStore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_petstore_PetStoreList_To_v1alpha1_PetStoreList is an autogenerated conversion function.
func Convert_petstore_PetStoreList_To_v1alpha1_PetStoreList(in *petstore.PetStoreList, out *PetStoreList, s conversion.Scope) error {
	return autoConvert_petstore_PetStoreList_To_v1alpha1_PetStoreList(in, out, s)
}

func autoConvert_v1alpha1_PetStoreSpec_To_petstore_PetStoreSpec(in *PetStoreSpec, out *petstore.PetStoreSpec, s conversion.Scope) error {
	out.PetList = *(*[]petstore.Pet)(unsafe.Pointer(&in.PetList))
	return nil
}

// Convert_v1alpha1_PetStoreSpec_To_petstore_PetStoreSpec is an autogenerated conversion function.
func Convert_v1alpha1_PetStoreSpec_To_petstore_PetStoreSpec(in *PetStoreSpec, out *petstore.PetStoreSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PetStoreSpec_To_petstore_PetStoreSpec(in, out, s)
}

func autoConvert_petstore_PetStoreSpec_To_v1alpha1_PetStoreSpec(in *petstore.PetStoreSpec, out *PetStoreSpec, s conversion.Scope) error {
	out.PetList = *(*[]Pet)(unsafe.Pointer(&in.PetList))
	return nil
}

// Convert_petstore_PetStoreSpec_To_v1alpha1_PetStoreSpec is an autogenerated conversion function.
func Convert_petstore_PetStoreSpec_To_v1alpha1_PetStoreSpec(in *petstore.PetStoreSpec, out *PetStoreSpec, s conversion.Scope) error {
	return autoConvert_petstore_PetStoreSpec_To_v1alpha1_PetStoreSpec(in, out, s)
}

func autoConvert_v1alpha1_PetStoreStatus_To_petstore_PetStoreStatus(in *PetStoreStatus, out *petstore.PetStoreStatus, s conversion.Scope) error {
	out.Population = in.Population
	return nil
}

// Convert_v1alpha1_PetStoreStatus_To_petstore_PetStoreStatus is an autogenerated conversion function.
func Convert_v1alpha1_PetStoreStatus_To_petstore_PetStoreStatus(in *PetStoreStatus, out *petstore.PetStoreStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PetStoreStatus_To_petstore_PetStoreStatus(in, out, s)
}

func autoConvert_petstore_PetStoreStatus_To_v1alpha1_PetStoreStatus(in *petstore.PetStoreStatus, out *PetStoreStatus, s conversion.Scope) error {
	out.Population = in.Population
	return nil
}

// Convert_petstore_PetStoreStatus_To_v1alpha1_PetStoreStatus is an autogenerated conversion function.
func Convert_petstore_PetStoreStatus_To_v1alpha1_PetStoreStatus(in *petstore.PetStoreStatus, out *PetStoreStatus, s conversion.Scope) error {
	return autoConvert_petstore_PetStoreStatus_To_v1alpha1_PetStoreStatus(in, out, s)
}
